export const PLACE_ORDER_MSG_TYPE = 'broker/PlaceOrder'
export const CANCEL_ORDER_MSG_TYPE = 'broker/CancelOrder'
export const MINT_TOKEN_MSG_TYPE = 'broker/MintToken'
export const ADD_TOKEN_MSG_TYPE = 'broker/AddToken'
export const ADD_MARKET_MSG_TYPE = 'broker/AddMarket'

export const CREATE_ORACLE_TYPE = 'oracle/CreateOracle'
export const CREATE_PROPOSTION_TYPE = 'oracle/CreateProposition'
//export const CREATE_ORACLE_RESULT_TYPE = 'oracle/CreateOracleResult'
//export const CREATE_ORACLE_VOTER_TYPE = 'oracle/CreateOracleVoter'
