export const PLACE_ORDER_MSG_TYPE = 'broker/PlaceOrder'
export const CANCEL_ORDER_MSG_TYPE = 'broker/CancelOrder'
export const MINT_TOKEN_MSG_TYPE = 'broker/MintToken'
export const ADD_TOKEN_MSG_TYPE = 'broker/AddToken'
export const ADD_MARKET_MSG_TYPE = 'oracles/AddMarket'

export const CREATE_ORACLE_TYPE = 'oracles/CreateOracle'
export const CREATE_ORACLE_PROPOSTION_TYPE = 'oracles/CreateProposition'
export const CREATE_ORACLE_RESULT_TYPE = 'oracles/CreateOracleResult'
export const CREATE_ORACLE_VOTER_TYPE = 'oracles/CreateOracleVoter'
