export const PLACE_ORDER_MSG_TYPE = 'broker/PlaceOrder'
export const CANCEL_ORDER_MSG_TYPE = 'broker/CancelOrder'
export const MINT_TOKEN_MSG_TYPE = 'broker/MintToken'
export const ADD_TOKEN_MSG_TYPE = 'broker/AddToken'
export const ADD_ORACLE_RESULT_TYPE = 'broker/AddOracleResult'
